import { Country } from "./CountryList";

export const countries: Country[] = [
  {
    name: "France",
    slug: "france",
    image: "/images/france.png",
    region: "Europe",
    city: "Paris",
    population: "213M",
    description: "Known for its art, fashion, and iconic landmarks like the Eiffel Tower.",
    flag: "fr",
  },
  {
    name: "Japan",
    slug: "japan",
    image: "/images/japan.png",
    region: "Asia",
    city: "Tokyo",
    population: "213M",
    description: "A blend of ancient traditions and cutting-edge technology.",
    flag: "jp",
  },
  {
    name: "United State",
    slug: "usa",
    image: "/images/usa.png",
    region: "South America",
    city: "Washington D.C.",
    population: "213M",
    description: "A diverse nation with vibrant cities, natural wonders, and cultural landmarks from coast to coast.",
    flag: "us",
  },
  {
    name: "Italy",
    slug: "italy",
    image: "/images/italy.png",
    region: "South America",
    city: "Brasília",
    population: "213M",
    description: "Known for its Amazon rainforest, Carnival, and football passion.",
    flag: "it",
  },
  {
    name: "Brazil",
    slug: "brazil",
    image: "/images/brazil.png",
    region: "South America",
    city: "Brasília",
    population: "213M",
    description: "Known for its Amazon rainforest, Carnival, and football passion.",
    flag: "br",
  },
  {
    name: "Australia",
    slug: "australia",
    image: "/images/austalia.png",
    region: "Ocean",
    city: "Canberra",
    population: "213M",
    description: "A land of unique wildlife, stunning beaches, and the iconic Sydney Opera House. Adventure awaits down under.",
    flag: "au",
  },
]
